on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extension-csv: mbstring, bcmath
      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install

      - name: Check code styling
        run: ./vendor/bin/pint --test

      - name: Run tests
        run: php artisan test --min=30
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extension-csv: mbstring, bcmath
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: dep deploy phpconnect.tobexkee.xyz --tag=${{ env.GITHUB_REF }} -vvv
