on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extension-csv: mbstring, bcmath
      - name: install dependencies
        run: composer install
      - name: Check code quality
        run: vendor/bin/pint --test
      - name: Run unit tests
        run: php artisan test
