on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extension-csv: mbstring, bcmath
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: vendor/bin/pint
      - name: Run tests
        run: php artisan test
